version: "3.8"
services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=CharacterManager.py
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=character_manager
    depends_on:
      - mysql
    volumes:
      - .:/character_manager
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=character_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./001_setup.sql/001_setup.sql:/docker-entrypoint-initdb.d/001_setup.sql:ro
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
